name: Build and Test

on: [push]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Configure
      run: cmake -B build .
    - name: Build
      run: cmake --build build
    - name: Test
      run: make -C build test
